ignore:
  - 'vendor/*'
  - 'node_modules/*'
  - 'public_html/vendor/*'
  - 'public_html/src/node_modules/*'
  - 'public_html/libraries/*'

coverage:
  range: 0..22
  status:
    project:
      default:
        target: 27%

      tests:
        target: 100%
        paths:
          - 'tests/'
      app:
        target: 34%
        paths:
          - 'app/'

      api:
        target: 53%
        paths:
          - 'api/'
    patch: off

comment: off
